-- Solicitudes públicas para sumar un club o una licencia a Padbol Match.

CREATE TABLE IF NOT EXISTS public.solicitudes_licencia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_nombre TEXT NOT NULL,
  club_direccion TEXT,
  pais TEXT NOT NULL,
  ciudad TEXT NOT NULL,
  provincia_estado TEXT,
  club_telefono TEXT,
  club_email TEXT,
  club_web TEXT,
  deportes_canchas JSONB NOT NULL DEFAULT '{}'::jsonb,
  responsable_nombre TEXT NOT NULL,
  responsable_cargo TEXT,
  email TEXT NOT NULL,
  whatsapp TEXT,
  nombre_legal TEXT,
  numero_fiscal TEXT,
  fiscal_misma_que_club BOOLEAN NOT NULL DEFAULT TRUE,
  direccion_fiscal TEXT,
  pais_fiscal TEXT,
  mensaje TEXT,
  tipo_interes TEXT NOT NULL DEFAULT 'pendiente_definicion',
  estado TEXT NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente', 'aprobada', 'rechazada')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_solicitudes_licencia_estado_created
  ON public.solicitudes_licencia (estado, created_at DESC);

ALTER TABLE public.solicitudes_licencia ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.solicitudes_licencia FROM anon, authenticated;

COMMENT ON TABLE public.solicitudes_licencia IS
  'Solicitudes privadas enviadas desde la página pública para sumar un club.';
