/**
 * Catálogo de fuentes de generación PadCoins.
 * PadCoins es un sistema integral de participación — no solo reservas.
 */

export const PADCOINS_EARNING_SOURCE_STATUSES = Object.freeze({
  ACTIVE: 'active',
  PLANNED: 'planned',
  FUTURE: 'future',
});

export const PADCOINS_EARNING_SOURCE_CATEGORIES = Object.freeze({
  JUEGO_RESERVAS: 'juego_reservas',
  COMUNIDAD: 'comunidad',
  COMPETENCIA: 'competencia',
  FIDELIZACION_COMERCIAL: 'fidelizacion_comercial',
  RETENCION: 'retencion',
  PERFIL_ONBOARDING: 'perfil_onboarding',
});

export const PADCOINS_EARNING_CALCULATION_TYPES = Object.freeze({
  FIXED_PADCOINS: 'fixed_padcoins',
  PERCENTAGE_OF_TURN: 'percentage_of_turn',
  PERCENTAGE_OF_ORDER: 'percentage_of_order',
  TOURNAMENT_REWARD: 'tournament_reward',
  CAMPAIGN_RULE: 'campaign_rule',
  MANUAL_ADMIN_REWARD: 'manual_admin_reward',
});

export const PADCOINS_EARNING_ADMIN_SCOPES = Object.freeze({
  SEDE: 'sede',
  PLATFORM: 'platform',
});

export const PADCOINS_EARNING_SOURCES_CATALOG = Object.freeze([
  // ─── juego_reservas ───────────────────────────────────────────────────────
  {
    key: 'reserva_jugada',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.JUEGO_RESERVAS,
    label: 'Reserva jugada',
    description: 'Acreditación por reserva completada en la sede. Base actual del cálculo proporcional.',
    default_enabled: true,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.PERCENTAGE_OF_TURN,
    default_value: null,
    editable_by_sede: true,
    limits: { daily_max: null, monthly_max: null, per_source_max: 1 },
    requires_source_id: true,
    legacy_referencia_tipo: 'reserva',
    status: PADCOINS_EARNING_SOURCE_STATUSES.ACTIVE,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.SEDE,
  },
  {
    key: 'creador_partido',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.JUEGO_RESERVAS,
    label: 'Creador del partido',
    description: 'Recompensa al jugador que crea y concreta un partido abierto en la sede.',
    default_enabled: false,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.FIXED_PADCOINS,
    default_value: 150,
    editable_by_sede: true,
    limits: { daily_max: 3, monthly_max: null, per_source_max: 1 },
    requires_source_id: true,
    status: PADCOINS_EARNING_SOURCE_STATUSES.PLANNED,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.SEDE,
  },
  {
    key: 'jugador_se_suma_partido',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.JUEGO_RESERVAS,
    label: 'Jugador que se suma a un partido',
    description: 'Incentivo por sumarse a un partido abierto y jugarlo.',
    default_enabled: false,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.FIXED_PADCOINS,
    default_value: 75,
    editable_by_sede: true,
    limits: { daily_max: 5, monthly_max: null, per_source_max: 1 },
    requires_source_id: true,
    status: PADCOINS_EARNING_SOURCE_STATUSES.PLANNED,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.SEDE,
  },

  // ─── competencia ──────────────────────────────────────────────────────────
  {
    key: 'inscripcion_torneo',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.COMPETENCIA,
    label: 'Inscripción a torneo',
    description: 'PadCoins por inscribirse y confirmar participación en un torneo de la sede.',
    default_enabled: false,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.TOURNAMENT_REWARD,
    default_value: 250,
    editable_by_sede: true,
    limits: { daily_max: null, monthly_max: null, per_source_max: 1 },
    requires_source_id: true,
    status: PADCOINS_EARNING_SOURCE_STATUSES.PLANNED,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.SEDE,
  },
  {
    key: 'partido_torneo_jugado',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.COMPETENCIA,
    label: 'Partido de torneo jugado',
    description: 'Acreditación por disputar un partido dentro de un torneo.',
    default_enabled: false,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.TOURNAMENT_REWARD,
    default_value: 100,
    editable_by_sede: true,
    limits: { daily_max: null, monthly_max: null, per_source_max: 1 },
    requires_source_id: true,
    status: PADCOINS_EARNING_SOURCE_STATUSES.PLANNED,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.SEDE,
  },
  {
    key: 'avance_torneo',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.COMPETENCIA,
    label: 'Avance en torneo',
    description: 'Bonificación por avanzar de fase en un torneo.',
    default_enabled: false,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.TOURNAMENT_REWARD,
    default_value: 500,
    editable_by_sede: false,
    limits: { daily_max: null, monthly_max: null, per_source_max: 1 },
    requires_source_id: true,
    status: PADCOINS_EARNING_SOURCE_STATUSES.FUTURE,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.SEDE,
  },
  {
    key: 'campeon_torneo',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.COMPETENCIA,
    label: 'Campeón de torneo',
    description: 'Premio PadCoins por ganar un torneo.',
    default_enabled: false,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.TOURNAMENT_REWARD,
    default_value: 1500,
    editable_by_sede: false,
    limits: { daily_max: null, monthly_max: null, per_source_max: 1 },
    requires_source_id: true,
    status: PADCOINS_EARNING_SOURCE_STATUSES.FUTURE,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.SEDE,
  },
  {
    key: 'subcampeon_torneo',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.COMPETENCIA,
    label: 'Subcampeón de torneo',
    description: 'Premio PadCoins por segundo puesto en un torneo.',
    default_enabled: false,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.TOURNAMENT_REWARD,
    default_value: 1000,
    editable_by_sede: false,
    limits: { daily_max: null, monthly_max: null, per_source_max: 1 },
    requires_source_id: true,
    status: PADCOINS_EARNING_SOURCE_STATUSES.FUTURE,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.SEDE,
  },

  // ─── comunidad ────────────────────────────────────────────────────────────
  {
    key: 'invitacion_aceptada',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.COMUNIDAD,
    label: 'Invitación aceptada',
    description: 'PadCoins cuando un invitado se registra o juega por primera vez gracias a la invitación.',
    default_enabled: false,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.FIXED_PADCOINS,
    default_value: 500,
    editable_by_sede: false,
    limits: { daily_max: 3, monthly_max: 10, per_source_max: 1 },
    requires_source_id: true,
    status: PADCOINS_EARNING_SOURCE_STATUSES.PLANNED,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.PLATFORM,
  },
  {
    key: 'resena_util',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.COMUNIDAD,
    label: 'Reseña útil',
    description: 'Reconocimiento por reseñas de sede o experiencia que aportan valor a la comunidad.',
    default_enabled: false,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.FIXED_PADCOINS,
    default_value: 100,
    editable_by_sede: true,
    limits: { daily_max: 2, monthly_max: 5, per_source_max: 1 },
    requires_source_id: true,
    status: PADCOINS_EARNING_SOURCE_STATUSES.PLANNED,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.SEDE,
  },

  // ─── perfil_onboarding ────────────────────────────────────────────────────
  {
    key: 'perfil_completo',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.PERFIL_ONBOARDING,
    label: 'Perfil completo',
    description: 'Bonificación única por completar el perfil del jugador.',
    default_enabled: false,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.FIXED_PADCOINS,
    default_value: 250,
    editable_by_sede: false,
    limits: { daily_max: null, monthly_max: null, per_source_max: 1 },
    requires_source_id: false,
    status: PADCOINS_EARNING_SOURCE_STATUSES.PLANNED,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.PLATFORM,
  },

  // ─── fidelizacion_comercial ───────────────────────────────────────────────
  {
    key: 'campana_sede',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.FIDELIZACION_COMERCIAL,
    label: 'Campaña de sede',
    description: 'Multiplicadores o bonificaciones definidos en campañas PadCoins de la sede.',
    default_enabled: true,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.CAMPAIGN_RULE,
    default_value: null,
    editable_by_sede: true,
    limits: { daily_max: null, monthly_max: null, per_source_max: null },
    requires_source_id: true,
    status: PADCOINS_EARNING_SOURCE_STATUSES.ACTIVE,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.SEDE,
  },
  {
    key: 'compra_eshop',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.FIDELIZACION_COMERCIAL,
    label: 'Compra en e-shop',
    description: 'PadCoins por compras futuras en la tienda de la sede o plataforma.',
    default_enabled: false,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.PERCENTAGE_OF_ORDER,
    default_value: 5,
    editable_by_sede: true,
    limits: { daily_max: null, monthly_max: null, per_source_max: 1 },
    requires_source_id: true,
    status: PADCOINS_EARNING_SOURCE_STATUSES.FUTURE,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.SEDE,
  },

  // ─── retencion ────────────────────────────────────────────────────────────
  {
    key: 'regreso_jugador_inactivo',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.RETENCION,
    label: 'Regreso de jugador inactivo',
    description: 'Incentivo para jugadores que vuelven a jugar tras un período de inactividad.',
    default_enabled: false,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.FIXED_PADCOINS,
    default_value: 300,
    editable_by_sede: true,
    limits: { daily_max: null, monthly_max: 1, per_source_max: 1 },
    requires_source_id: true,
    status: PADCOINS_EARNING_SOURCE_STATUSES.FUTURE,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.SEDE,
  },
  {
    key: 'racha_participacion',
    category: PADCOINS_EARNING_SOURCE_CATEGORIES.RETENCION,
    label: 'Racha de participación',
    description: 'Bonificación por mantener una racha de participación (reservas, partidos o torneos).',
    default_enabled: false,
    calculation_type: PADCOINS_EARNING_CALCULATION_TYPES.FIXED_PADCOINS,
    default_value: 500,
    editable_by_sede: true,
    limits: { daily_max: null, monthly_max: 1, per_source_max: 1 },
    requires_source_id: true,
    status: PADCOINS_EARNING_SOURCE_STATUSES.FUTURE,
    admin_scope: PADCOINS_EARNING_ADMIN_SCOPES.SEDE,
  },
]);

export const PADCOINS_EARNING_CATEGORY_LABELS = Object.freeze({
  [PADCOINS_EARNING_SOURCE_CATEGORIES.JUEGO_RESERVAS]: 'Juego y reservas',
  [PADCOINS_EARNING_SOURCE_CATEGORIES.COMUNIDAD]: 'Comunidad',
  [PADCOINS_EARNING_SOURCE_CATEGORIES.COMPETENCIA]: 'Competencia',
  [PADCOINS_EARNING_SOURCE_CATEGORIES.FIDELIZACION_COMERCIAL]: 'Fidelización comercial',
  [PADCOINS_EARNING_SOURCE_CATEGORIES.RETENCION]: 'Retención',
  [PADCOINS_EARNING_SOURCE_CATEGORIES.PERFIL_ONBOARDING]: 'Perfil y onboarding',
});

export const PADCOINS_EARNING_SOURCES_SETUP_MESSAGE =
  'PadCoins puede generarse por distintas acciones del ecosistema. Las reservas son una base actual de cálculo, pero el sistema está preparado para sumar torneos, partidos, invitaciones, reseñas, perfil, e-shop y campañas.';
