import test from 'node:test';
import assert from 'node:assert/strict';
import {mountNationalTeamRoutes} from './nationalTeams.js';
const ids=Array.from({length:9},(_,i)=>`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`);
function fixture({role={rol:'jugador'},user={id:ids[0]},tournament={},team={},match={},marker=[],stored=null,rpcError=null,rpcData=null,readError=null}={}){
 const t={id:10,sede_id:7,deporte:'padbol',modalidad_plantel:'selecciones',estado:'inscripcion',costo_inscripcion:0,inscripcion_monto:null,...tournament};
 const e={id:20,torneo_id:10,nombre:'QA National',creador_id:ids[0],cupo_maximo:8,equipo_abierto:true,plantel_revision:1,inscripcion_estado:'confirmado',jugadores:ids.slice(0,8).map((id)=>({id,user_id:id,nombre:'QA',email:'private@example.invalid',estado:'confirmado'})),solicitudes:[{user_id:ids[8],nombre:'Request',email:'private@example.invalid'}],...team};
 const m={id:30,torneo_id:10,equipo_a_id:20,equipo_b_id:21,estado:'pendiente',...match};
 const calls=[];const routes=new Map();const data={torneos:t,equipos:e,partidos:m,scoreboard_partidos:marker,torneo_partido_alineaciones:stored};
 const db={from(table){calls.push(['read',table]);const q={select(){return q;},eq(){return q;},order(){return q;},limit(){return q;},maybeSingle:async()=>({data:data[table],error:readError}),then(resolve,reject){return Promise.resolve({data:table==='equipos'?[e]:data[table],error:readError}).then(resolve,reject);}};return q;},rpc:async(name,params)=>{calls.push(['rpc',name,params]);return {data:rpcData??(name==='guardar_plantel_seleccion'?{status:'saved',equipo:e}:{torneo_id:10,partido_id:30,equipo_id:20,iniciales:params.p_iniciales,suplentes:params.p_suplentes,revision:params.p_revision+1}),error:rpcError};}};
 const app=Object.fromEntries(['get','post','put'].map(method=>[method,(path,handler)=>routes.set(method+' '+path,handler)]));mountNationalTeamRoutes(app,{db,getAuthenticatedUser:async()=>({user,status:user?null:401}),getRole:async()=>role});
 const call=async(method,path,body={})=>{const res={statusCode:200,status(n){this.statusCode=n;return this;},json(value){this.body=value;return this;}};await routes.get(method+' '+path)({params:{id:'10',equipoId:'20',partidoId:'30'},body},res);return res;};return {call,calls,t,e};
}
const base='/api/torneos/:id/selecciones';const lineup='/api/torneos/:id/partidos/:partidoId/equipos/:equipoId/alineacion';const body={iniciales:ids.slice(0,2),suplentes:ids.slice(2,4),expected_revision:0};
test('anonymous request rejects before any database read',async()=>{const f=fixture({user:null});assert.equal((await f.call('get',base)).statusCode,401);assert.equal(f.calls.length,0);});
test('authenticated list uses safe player identity fields, capacity and no private requests',async()=>{const f=fixture();const r=await f.call('get',base);assert.equal(r.statusCode,200);assert.equal(r.body.equipos[0].equipo_abierto,true);assert.equal(r.body.equipos[0].jugadores[0].email,undefined);assert.equal(r.body.equipos[0].solicitudes,undefined);});
test('unrelated player, national administrator and wrong-club administrator cannot edit',async()=>{for(const role of [{rol:'jugador'},{rol:'admin_nacional',pais:'Argentina'},{rol:'admin_club',sede_id:8}]){const f=fixture({user:{id:ids[8]},role});assert.equal((await f.call('put',lineup,body)).statusCode,403);assert.equal(f.calls.some(c=>c[0]==='rpc'),false);}});
test('captain, tournament club administrator and superadministrator can save exact four',async()=>{for(const actor of [{user:{id:ids[0]},role:{rol:'jugador'}},{user:{id:ids[8]},role:{rol:'admin_club',sede_id:7}},{user:{id:ids[8]},role:{rol:'super_admin'}}]){const f=fixture(actor);const r=await f.call('put',lineup,body);assert.equal(r.statusCode,200);assert.equal(r.body.alineacion.revision,1);assert.deepEqual(r.body.alineacion.iniciales,ids.slice(0,2));}});
test('result, canceled tournament, unconfirmed team and opened scoreboard disable editing',async()=>{for(const patch of [{match:{estado:'finalizado'}},{tournament:{estado:'cancelado'}},{team:{inscripcion_estado:'pendiente'}},{marker:[{id:9}]}]){const f=fixture(patch);assert.equal((await f.call('get',lineup)).body.can_edit,false);assert.equal((await f.call('put',lineup,body)).statusCode,409);assert.equal(f.calls.some(c=>c[0]==='rpc'),false);}});
test('lineup receipt must identify exact match, team, tournament and positive revision',async()=>{for(const rpcData of [{torneo_id:99,partido_id:30,equipo_id:20},{torneo_id:10,partido_id:31,equipo_id:20},{torneo_id:10,partido_id:30,equipo_id:20,iniciales:ids.slice(0,2),suplentes:ids.slice(2,4),revision:0}]){const f=fixture({rpcData});assert.equal((await f.call('put',lineup,body)).statusCode,503);}});
test('revision conflict is409 and unknown database failure cannot claim success',async()=>{for(const [code,status] of [['40001',409],['22023',409],['XX000',503]]){const f=fixture({rpcError:{code}});assert.equal((await f.call('put',lineup,body)).statusCode,status);}});
test('draft can have one captain and source receipt never leaks other requests',async()=>{const f=fixture({team:{jugadores:[{id:ids[0],nombre:'Captain',estado:'confirmado'}],inscripcion_estado:'pendiente'}});const r=await f.call('post',base,{nombre:'National QA',cupo_maximo:8});assert.equal(r.statusCode,201);assert.equal(r.body.jugadores.length,1);assert.equal(r.body.can_confirm,false);const outsider=fixture({user:{id:ids[8]}});const request=await outsider.call('post',base+'/:equipoId/solicitudes');assert.equal(request.statusCode,200);assert.deepEqual(request.body.solicitudes,[]);assert.equal(request.body.can_confirm,false);});
test('capacity9, invalid roster and duplicate members rejected without storage writes',async()=>{const f=fixture();assert.equal((await f.call('post',base,{nombre:'QA',cupo_maximo:9})).statusCode,400);assert.equal((await f.call('put',base+'/:equipoId/plantel',{user_ids:[ids[0],ids[0]],expected_revision:1})).statusCode,400);assert.equal(f.calls.some(c=>c[0]==='rpc'),false);});
test('paid or unknown fee cannot be confirmed by this free enrollment endpoint',async()=>{for(const tournament of [{costo_inscripcion:10},{costo_inscripcion:null,inscripcion_monto:null}]){const f=fixture({tournament});const r=await f.call('post',base+'/:equipoId/confirmar',{expected_revision:1});assert.equal(r.statusCode,409);assert.equal(r.body.code,'NATIONAL_PAYMENT_FLOW_REQUIRED');assert.equal(f.calls.some(c=>c[0]==='rpc'),false);}});
test('legacy doubles has no declaration requirement and performs no lineup or scoreboard read',async()=>{const f=fixture({tournament:{modalidad_plantel:'dobles'}});const r=await f.call('get',lineup);assert.equal(r.body.required,false);assert.equal(r.body.alineacion,null);assert.equal(f.calls.some(c=>['scoreboard_partidos','torneo_partido_alineaciones'].includes(c[1])),false);});
test('failed list read is an error rather than a false empty list',async()=>{const f=fixture({readError:{code:'XX000'}});assert.equal((await f.call('get',base)).statusCode,503);});

test('real opened inscription state aliases allow draft enrollment and editable declarations',async()=>{for(const estado of ['abierto','inscripcion_abierta','inscripcion']){const f=fixture({tournament:{estado}});assert.equal((await f.call('post',base,{nombre:'QA',cupo_maximo:8})).statusCode,201);assert.equal((await f.call('get',lineup)).body.can_edit,true);assert.equal((await f.call('get',base+'/:equipoId')).body.can_confirm,true);}});
test('list management capability comes from actual captain or authorized tournament scope',async()=>{for(const [role,user,expected] of [[{rol:'admin_nacional',pais:'Argentina'},{id:ids[8]},false],[{rol:'admin_club',sede_id:8},{id:ids[8]},false],[{rol:'super_admin'},{id:ids[8]},true],[{rol:'jugador'},{id:ids[0]},true]]){const f=fixture({role,user});assert.equal((await f.call('get',base)).body.equipos[0].can_manage,expected);}});

test('arbitrary-profile addition capability is real admin scope even when actor is also captain',async()=>{for(const [role,expected] of [[{rol:'jugador'},false],[{rol:'admin_nacional',pais:'Argentina'},false],[{rol:'admin_club',sede_id:8},false],[{rol:'admin_club',sede_id:7},true],[{rol:'super_admin'},true]]){const f=fixture({role,user:{id:ids[0]}});const r=await f.call('get',base+'/:equipoId');assert.equal(r.body.can_manage,true);assert.equal(r.body.can_add_profiles,expected);}});
