-- QA preparada: crea la tabla y el bucket del "recorrido externo" (reconocimiento de nivel).
-- NO se aplica de forma remota en este paso. Revisar antes de ejecutar en la BD de QA.
BEGIN;

CREATE TABLE IF NOT EXISTS public.recorridos_externos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  email text,
  origen text NOT NULL,
  categorias text[] NOT NULL DEFAULT '{}',
  comentario text,
  capturas_paths text[] NOT NULL DEFAULT '{}',
  estado text NOT NULL DEFAULT 'recibido'
    CHECK (estado IN ('recibido','en_revision','requiere_informacion','aprobado','rechazado')),
  datos_reconocidos jsonb NOT NULL DEFAULT '{}'::jsonb,
  nota_revision text,
  revisar_antes_de timestamptz NOT NULL DEFAULT (now() + interval '24 hours'),
  revisado_por uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  revisado_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS recorridos_externos_user_created_idx
  ON public.recorridos_externos (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS recorridos_externos_estado_deadline_idx
  ON public.recorridos_externos (estado, revisar_antes_de);
CREATE UNIQUE INDEX IF NOT EXISTS recorridos_externos_una_activa_por_jugador_idx
  ON public.recorridos_externos (user_id)
  WHERE estado IN ('recibido', 'en_revision');

ALTER TABLE public.recorridos_externos ENABLE ROW LEVEL SECURITY;

-- El backend usa service_role (bypass RLS); el jugador solo lee su propio recorrido.
DROP POLICY IF EXISTS "jugador lee su recorrido externo" ON public.recorridos_externos;
CREATE POLICY "jugador lee su recorrido externo"
  ON public.recorridos_externos FOR SELECT
  USING (auth.uid() = user_id);

-- Evidencia privada: bucket no público, con tipos y tamaño acotados.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'recorridos-externos',
  'recorridos-externos',
  false,
  8388608,
  ARRAY['image/jpeg','image/png','image/webp','application/pdf']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

COMMENT ON TABLE public.recorridos_externos IS
  'Solicitudes de jugadores para reconocer recorrido deportivo previo; evidencia privada y revisión en hasta 24 horas.';

COMMIT;
